### ISSUE TITLE
Execution of rbm with Nengo 2.0.0 / 2.1.0 

### ISSUE THREAD

**Issue by MenelikV** [hunse/mnist-rbm#1]
Hello everybody,

I tried to execute the script rbm.py with Nengo 2.0.0 and 2.1.0. For both, the code failed to execute properly.
With the 2.0.0 version, the error is :

Traceback (most recent call last):
  File "rbm.py", line 76, in <module>
    find_neuron_params.find_params(savefile=neuron_params_file, show=False)
  File "/home/menelou/Downloads/mnist-rbm-master/find_neuron_params.py", line 59, in find_params
    r = residual(encoders, max_rates, intercepts, eval_points)
  File "/home/menelou/Downloads/mnist-rbm-master/find_neuron_params.py", line 35, in residual
    d = nengo.decoders.lstsq_L2nz(A, y)
AttributeError: 'module' object has no attribute 'lstsq_L2nz'

Concerning the orther version, the module distributions in nengo.utils.distribution does not seem to exist (was it renamed ?)

Has anyone an idea of solutions ?

Thanks in advance,

Ménélik.

**Comment by hunse** [comment]
Sorry, I just haven't kept this up to date. I'll update it for Nengo 2.0.0/2.0.1 (I think it should be an easy fix).

**Comment by hunse** [comment]
Okay, I've pushed a fix to `master`.

**Comment by MenelikV** [comment]
Thanks a lot, it works ! :)
